### ISSUE TITLE
Alt-tab bug

### ISSUE THREAD

**Issue by ezluci** [for-loop9/vlither#1]
I use Arch Linux with PlasmaShell and X11.

While in fullscreen mode, press mouse1, alt-tab to another window, alt-tab back to the game, release mouse1. It seems that now the game is not receiving **any** updates from the mouse, and the cursor position is stuck to the one before the first alt-tab (check image). The game still receives input from the keyboard.

This bug doesn't require you to be actually in a game, you can recreate it in the main menu. You can make the mouse input work again by alt-tabbing without mouse1 pressed.

The screenshot doesn't show my cursor, but it **isn't** where the laser assist shows.
![image](https://github.com/user-attachments/assets/a26e804e-256f-4d4a-952e-07becd28552d)

Let me know if you need any additional information.

**Comment by for-loop9** [comment]
Interesting, I can't reproduce it on Ubuntu 24.04, everything works fine. My best guess is - it's X11 mouse issues on Arch. Since I don't have Arch, perhaps the best way to find out is to see whether `mouse_pos_callback()` in `ig_mouse.c` is being triggered after you Alt-Tab back into the program (a breakpoint, or just a print statement).

**Comment by ezluci** [comment]
I'm sorry, while testing this bug I was actually using Wayland instead of X11. On X11 this bug does not occur, so it looks like the problem is with Wayland, and not with the game. You may close this issue.
